server:
  port: 2333
  address: 0.0.0.0

spring:
  main:
    banner-mode: "off"

lavalink:
  plugins:
    # Add plugin paths here if needed later
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false

metrics:
  prometheus:
    enabled: true

logging:
  level:
    root: INFO
    lavalink: INFO
