server:
  port: 2333
  address: 0.0.0.0

spring:
  main:
    banner-mode: "off"

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
